### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by dustin** [dustin/go-coap#24]
```
--- FAIL: TestEncodeSeveral (0.00s)
	message_test.go:274: Expected []string{"a", "b", "c", "d", "e", "f", "h", "g", "i", "j"}, got []string{"f", "a", "h", "d", "e", "b", "c", "g", "i", "j"}
```

**Comment by vtrushkin** [comment]
Do you get same string array each time in this test case?
```
[vtrushkin@TARDIS go-coap]$ git pull origin master
From https://github.com/dustin/go-coap
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
[vtrushkin@TARDIS go-coap]$ git hist -1
* 10a6085 2015-07-27 | Implement extended option headers (HEAD -> master, origin/master, origin/HEAD) [Vyacheslav Trushkin]
[vtrushkin@TARDIS go-coap]$ go test
PASS
ok  	github.com/dustin/go-coap	0.002s
```

**Comment by dubek** [comment]
I think found the problem. In `message.go:469` we should have:

```go
	sort.Stable(&m.opts)
```

to ensure that the sort doesn't change the order of options with the same option ID (for example, the parts of the URLPath option).

Also while we're around this, it might be simple to have this implementation for `SetPath`:

```go
func (m *Message) SetPath(s []string) {
	m.SetOption(URIPath, s)
}
```

(because `SetOption` already knows how to deal with slices.)

**Comment by dustin** [comment]
Oh cool, thanks.

SetOption for SetPath seems to do the trick without introducing any test
failures as well
